name: laptrinhdidong
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.1
  firebase_database: ^11.2.0
  cloud_firestore: ^5.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  - lib/assets/fonts/
  fonts:
    - family: Magra
      fonts:
        - asset: lib/assets/fonts/Magra-Bold.ttf 
          weight: 600
        - asset: lib/assets/fonts/Magra-Regular.ttf 
          weight: 400
     